### ISSUE TITLE
Minor Issue: domain naming

### ISSUE THREAD

**Issue by rmorshea** [astrofrog/numtraits#19]
`"positive"` as `x > 0` and `"strictly-positive"` as `x >= 0` is unintuitive.

Using these conventions:
- `"positive"` as `x > 0` and `"non-negative"` as `x >= 0`
- `"strictly-positive"` as `x > 0` and `"positive"` as `x >= 0`

would be far less ambiguous.

 _(same goes for negatives)_

**Comment by astrofrog** [comment]
@rmorshea - I thought that I had it so that `positive` was `x >= 0` and `strictly-positive` was `x > 0`? If this is not the case, I would consider that a bug.

**Comment by rmorshea** [comment]
Issue in [line 130](https://github.com/astrofrog/numtraits/blob/master/numtraits.py#L130) (same for negative). I can write a quick pr though. What convention do you prefer? `"non-negative"` or `"strictly-positive"`?

**Comment by rmorshea** [comment]
Ugh, my bad, mixed up the direction of `>`/`<`. No issue.

**Comment by burnpanck** [comment]
While reviewing #20, I ran into the same confusion as @rmorshea. To fight that confusion, I was going to suggest that maybe the validation should be implemented literally as `np.all(num_value >= 0.)` for a _positive_ trait, such that it raises `if not np.all(num_value >= 0.)`. However, that changes behaviour for `NaN` values.

What is your take on `NaN` values, should they be accepted? There is a case for both sides, often one would like to use `NaN` to indicate missing values, in which case they probably should be accepted. However, in situations where the traited code literally expects `value >= 0.` to be true, `NaN` would fail and therefore should be rejected. So how about interpreting the domains literally and distinguish between `positive`, `strictly-positive`, `non-negative` and `strictly-non-negative`? This would result in  a slight change in behaviour for the currently existing domain names. The alternative would be a separate flag `allow_nan` that defaults to `True` for backwards compatibility. Or, my preferred option, have both, and let the domain select the default value for `allow_nan`, but keep the flag for explicitness and to allow suppression of `NaN` values without specifying a domain.
